apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: "kserve-custom-model"
spec:
  predictor:
    containers:
    - image: pongsakornpongsutiyakorn/kserve-shap-model
      resources:
        requests:
          memory: "2048Mi"
          cpu: "250m"
        limits:
          memory: "2048Mi"
          cpu: "500m"
          env:
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-secret
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-secret
            key: AWS_SECRET_ACCESS_KEY
      - name: AWS_DEFAULT_REGION
        valueFrom:
          secretKeyRef:
            name: aws-secret
            key: AWS_DEFAULT_REGION